### ISSUE TITLE
Disabling referer headers

### ISSUE THREAD

**Issue by hrj** [amq/firefox-debloat#12]
#### `network.http.sendReferheader`
     0 means never send, breaks many sites
     1 means send only for clicked links, works fine for most sites
     2 (default) means send always.

Recommendation can be to set to 0 or 1. More details [here](http://kb.mozillazine.org/Network.http.sendRefererHeader).

### `network.http.sendSecureXSiteReferrer`
  `true` (default) Send referer header when navigating from one https site to another.
  `false`  Don't send referer header when navigating from one https site to another

Recommendation can be `false`. More details [here](http://kb.mozillazine.org/Network.http.sendSecureXSiteReferrer)

**Comment by amq** [comment]
```This list aims to block core Firefox features which *actively* leak data to third-party services.```

```We are not breaking the browsing experience, so you won't find things like spoofing referrers and canvas properties here.```
