### ISSUE TITLE
Disable leaking list of plugins

### ISSUE THREAD

**Issue by jomo** [amq/firefox-debloat#8]
### `plugins.enumerable_names`

By default (`*`), websites can get a list of plugins, their version & details via `navigator.plugins`.
You can set this option to an empty string, and websites will not see any Plugins:
```js
PluginArray { length: 0 }
```

However, this does break some sites (e.g. Deezer) because they (wrongfully) use this API to test if a user has, for example, Flash installed. If you want to allow this, you can set the configuration to `Shockwave Flash`. That will only return details about the Flash plugin.

Details about a Plugin look like this:
```js
Plugin { 0: MimeType, 1: MimeType, application/x-shockwave-flash: MimeType, application/futuresplash: MimeType, description: "Shockwave Flash 18.0 r0", filename: "Flash Player.plugin", version: "18.0.0.194", name: "Shockwave Flash", length: 2 }
```

----

See also: [Panopticlick](https://panopticlick.eff.org/index.php?action=log&js=yes).

**Comment by amq** [comment]
It would be great to get a list of plugins of 'the most generic' Firefox and use that instead of a blank value.

**Comment by kargakis** [comment]
> It would be great to get a list of plugins of 'the most generic' Firefox and use that instead of a blank value.

According to Panopticlick an undefined value for browser plugins ie. an empty value can be found in one per 10.69 browsers, which is a very good number to start with.

**Comment by jomo** [comment]
Great, apparently this option [was recently disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1169945) :/
